core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
    #path('about/', include('about.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.project_details, name='project_details'),
    re_path(r'^about/', views.about, name='about'),
]

projects/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    language = models.CharField(max_length=100)
    url = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.title


class Images(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images')



class Certificates(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    url = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.title

projects/forms.py
from django import forms


class ContactForm(forms.Form):
    template_name = 'projects/form_snippet.html'
    name = forms.CharField(label='Name', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    sender = forms.EmailField(widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    subject = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control'}))

projects/views.py
from django.shortcuts import render
from .models import Project, Images, Certificates

# Create your views here.


def index(request):
    projects = Project.objects.all()
    certificates = Certificates.objects.all()

    context = {
        'page_title': "Mishary",
        'projects': projects,
        'certificates': certificates,
    }
    return render(request, 'index.html', context)


def project_details(request, pk):
    project = Project.objects.get(pk=pk)
    context = {
        'page_title': "project",
        'project': project,
    }
    return render(request, 'projects/project_details.html', context)


def about(request):
    context = {
        'page_title': "about",
    }
    return render(request, 'projects/about.html', context)

projects/templates/projects/about.html
{% extends 'base.html'%}
{% load static %}
{% block page_title %}
<title>{{ page_title|capfirst }}</title>
{% endblock %}
{% block sections %}
<div class="container project-container">
    <div class="content-container text-center pt-3 mt-4 pb-4 px-3">
        <h3>Page Under Devolopment</h3>
        <img class="soon-img" src="{%static 'projects/images/Website-Maintenance.gif'%}" alt="soon">

    </div>
</div>
{% endblock sections %}

projects/templates/projects/form_snippet.html
{% for field in form %}
<div class="form-group">
    {{ field.errors }}
    <label for="{{ field.id_for_label }}" class="col-form-label text-dark">{{ field.label }}:</label>
    {{field}}
</div>
{% endfor %}

projects/templates/projects/project_details.html
{% extends 'base.html'%}
{% load static %}

{% block page_title %}
<!--  if the project has a title display the title in the {title tag},
    else just display Project for the title  -->
{% if project.title %}
<title>Project - {{ project.title }}</title>
{% else %}
<title>Project</title>
{% endif %}
{% endblock page_title %}

{% block sections %}
<!-- ***************  Project  **************** -->
<div class="container project-container">
    <div class="content-container py-2 px-3">
        <h3>{{ project.title }}</h3>

        <div id="heroCarousel" data-bs-interval="5000" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                {% for image in project.images_set.all %}
                <div class="carousel-item my-4 {% if forloop.first %}active {% endif %}">
                    <div class="slider">
                        <img src="{{ image.image.url }}" alt="{{ image.id }}">
                    </div>
                </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        <div class="project-content">
            <div class="technology">
                <h6>{{project.technology}}</h6>
                <h6>{{project.language}}</h6>
            </div>
            <p>{{project.description}}</p>
            {% if project.url %}
            <a class=" btn btn-outline-dark mb-2" href="{{ project.url }}" target="_blank">{{ project.title }}
                URL</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock sections %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300;400;600;700&display=swap" rel="stylesheet"> -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'projects/images/smallmalj.jpg' %}">
    {% block page_title %}
    {% endblock %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" type="text/css" href="{% static 'projects/style.css' %}">
    <script src="https://unpkg.com/scrollreveal"></script>
    <!-- Cookies popup cdn and event listener -->
    <script src="https://cdn.websitepolicies.io/lib/cookieconsent/1.0.3/cookieconsent.min.js" defer></script>
    <script>window.addEventListener("load", function () { window.wpcc.init({ "colors": { "popup": { "background": "#191645", "text": "#fff", "border": "#555555" }, "button": { "background": "#43C6AC", "text": "#fff" } }, "position": "bottom", "corners": "small", "transparency": "5", "fontsize": "normal", "content": { "href": "https://www.websitepolicies.com/policies/view/b17ahyv7" } }) });</script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-7WKVZVENN4"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'G-7WKVZVENN4');
    </script>
</head>

<body>
    <!-- ***************  Navbar  **************** -->

    <header class="primary-header">
        <div class="logo-container">
            <a href="{% url 'index'%}">
                <img class="logo" src="{% static 'projects/images/M-ALJ-logo-b.png'%}" alt="Mishary Portfolio">
            </a>
        </div>

        <!-- Open and Close Menu the text is hidddin but not for the screan reader -->
        <button class="mobile-nav-toggle" aria-controls="primary-navigation" aria-expanded="false">
            <span class="sr-only">Menu</span>
        </button>

        <nav>
            <ul id="primary-navigation" data-visible="false" class="primary-navigation flex">
                <li><a href="{% url 'about' %}"><span aria-hidden="true">00</span>About</a></li>
                <li><a href="{% url 'index' %}#projects"><span aria-hidden="true">01</span>Projects</a></li>
                <li><a href="{% url 'index' %}#education"><span aria-hidden="true">02</span>Education</a></li>
                <li><a href="#contacts"><span aria-hidden="true">03</span>Contacs</a></li>
            </ul>
        </nav>
    </header>

    {% block content %}
    {% endblock %}

    <div class="sections-container">

        {% block sections %}
        {% endblock %}

        <!-- *****************  CONTACT INFO / SOCIAL MEDIA  ***************** -->
        <footer id="contacts">
            <div class="container pb-2">
                <hr>
                <div class="px-3">
                    <h2>Contact</h2>

                    <section class="section-info">

                        <!-- Social media and contact links. Add or remove any networks. -->
                        <ul>
                            <!-- Google -->
                            <a class="btn btn-outline-dark btn-floating anim-a" href="mailto:alj.mishary@gmail.com"
                                role="button">
                                <i class="fa fa-google"></i> \ alj.mishary@gmail.com</a>
                            <!-- Github -->
                            <a class="btn btn-outline-dark btn-floating m-1 anim-a" href="https://github.com/MisharyAlj"
                                role="button" target="_blank"><i class="fa fa-github"></i></a>
                        </ul>
                    </section>
                </div>
            </div>
        </footer>
    </div>

    <!-- Modal 
    <div class="modal fade" id="contactMeModal" tabindex="-1" role="dialog" aria-labelledby="contactMeModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-dark" id="contactMeModalLabel">New message</h5>
                    <button type="button" class="btn close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{form}}
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <input type="submit" class="btn btn-primary" value="send" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>-->

    <!-- *****************  Scripts  ***************** -->

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" type="text/javascript"></script>
    <script src="{% static 'projects/nav.js' %}"></script>
    <script>
        ScrollReveal({
            reset: true,
            distance: '35px',
            duration: 800,
            delay: 200,
            easing: 'ease-out',
        });

        ScrollReveal().reveal('.logo-container', { delay: 200, origin: 'left', easing: 'ease-out' });
        ScrollReveal().reveal('h2, h4, .anim-p, .anim-a', { origin: 'left', interval: 300, easing: 'ease-out' });
        ScrollReveal().reveal('.about-content', { delay: 600, origin: 'left', easing: 'ease-out' });
        ScrollReveal().reveal('.card', { delay: 700, origin: 'bottom', easing: 'ease-out', interval: 350 });
    </script>
</body>

</html>

templates/index.html
{% extends 'base.html'%}
{% load static %}

{% block page_title %}
<title>{{ page_title | capfirst }}</title>
{% endblock page_title %}

{% block content %}
<!-- ***************  ABOUT / PROFILE  **************** -->
<section class="about-section" id="about">
    <div class="container">
        <div class="about-container">
            <div class="about-content d-inline-block p-2">
                <div class="about-text">
                    <h6><span> Hello,</span> my name is</h6>
                    <h1>Mishary Aljarie</h1>
                    <h6>And I'm a <span>Developer</span></h6>
                </div>
                <p><a class="btn btn-outline-dark mt-2" href="{% static 'projects/Mishary Aljarie - CV.pdf' %}"
                        download>Download CV</a>
                </p>
            </div>
        </div>
    </div>
</section>

{% endblock content %}
<!-- ************ PROJECTS / PORTFOLIO / EDUCATION  ************** -->
{% block sections %}
<section class="projects-section" id="projects">
    <div class="container pt-5 pb-2">
        <div class="content-container pt-1 pb-4 px-4">
            <h2>Projects</h2>
            <div class="masonry">
                {% for project in projects %}
                <!-- Project n -->
                <div class="masonry-item">
                    <div class="card card-shadow">
                        {% if project.images_set.all.0.image.url is not None %}
                        <img src="{{ project.images_set.all.0.image.url }}" class="card-img-top" alt="{{ project.title }}">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ project.title }}</h5>
                            <!--  only display the first 45 words in the descrption -->
                            <p class="card-text">{{ project.description|truncatewords:71 }}
                                {% if project.url %}
                                <a class="d-inline-block mb-2" href="{{ project.url }}" target="_blank">
                                    {{project.title}} URL</a>
                                {% endif %}
                            </p>
                            <a href="{{ project.pk }}"
                                class="btn btn-outline-dark {% if not project.url %} stretched-link {% endif %}">Read
                                more</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
</section>

<!-- ******************  EDUCATION & CERTIFICATIONS ****************** -->
<section class="education-section" id="education">
    <div class="container pb-4">
        <hr>
        <div class="content-container pt-1 pb-3 px-3">
            <h2>Education</h2>

            {% for certificat in certificates %}
            <section class="section-info mb-3">
                <ul>
                    <h5>{{ certificat.title }}</h4>
                        <p class="anim-p">{{ certificat.description }}</p>

                </ul>
            </section>
            {% endfor %}

        </div>
    </div>
</section>
{% endblock sections%}